version: "3.8"
services:
  webserver:
    container_name: polls_web_server_ngnix
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      # wwww
      - "./app/:/var/www/html"
      # conf
      - "./docker/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql
    restart: unless-stopped
  php:
    container_name: php_polls
    build:
      context: .
    volumes:
      # PHP APP
      - "./app/:/var/www/html"
      # xdebug conf
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    container_name: php_polls_mysql_db
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
  phpmyadmin:
    container_name: phpmyadmin_for_php_polls
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    links:
      - mysql
    env_file:
      - ".env"
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped

volumes:
  mysql:
